import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/app/**/*.{js,ts,jsx,tsx,mdx}", "./src/components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    colors: {
      inherit: "inherit",
      transparent: "transparent",
      current: "currentColor",
      blue: {
        DEFAULT: "rgb(var(--blue-default-rgb) / <alpha-value>)",
        contrast: "rgb(var(--blue-contrast-rgb) / <alpha-value>)",
        tone: "rgb(var(--blue-tone-rgb) / <alpha-value>)",
      },
      grey: {
        DEFAULT: "rgb(var(--grey-default-rgb) / <alpha-value>)",
        contrast: "rgb(var(--grey-contrast-rgb) / <alpha-value>)",
        tone: "rgb(var(--grey-tone-rgb) / <alpha-value>)",
      },
      sunken: {
        DEFAULT: "rgb(var(--sunken-default-rgb) / <alpha-value>)",
        tone: "rgb(var(--sunken-tone-rgb) / <alpha-value>)",
      },
      base: {
        DEFAULT: "rgb(var(--base-default-rgb) / <alpha-value>)",
        color: "rgb(var(--base-default-rgb) / <alpha-value>)",
        tone: "rgb(var(--base-tone-rgb) / <alpha-value>)",
      },
      elevated: {
        DEFAULT: "rgb(var(--elevated-default-rgb) / <alpha-value>)",
        tone: "rgb(var(--elevated-tone-rgb) / <alpha-value>)",
      },
      overlay: {
        DEFAULT: "rgb(0 0 0 / 0.3)",
      },
      hover: {
        DEFAULT: "rgb(var(--hover-default-rgb) / <alpha-value>)",
        soft: "rgb(var(--hover-default-rgb) / calc(0.5 * <alpha-value>))",
      },
      selected: {
        DEFAULT: "rgb(var(--selected-default-rgb) / <alpha-value>)",
      },
      outline: {
        DEFAULT: "rgb(var(--outline-default-rgb) / <alpha-value>)",
        soft: "rgb(var(--outline-default-rgb) / calc(0.5 * <alpha-value>))",
      },
      contrast: {
        primary: "rgb(var(--contrast-primary-rgb) / <alpha-value>)",
        secondary: "rgb(var(--contrast-secondary-rgb) / <alpha-value>)",
        tertiary: "rgb(var(--contrast-tertiary-rgb) / <alpha-value>)",
        disabled: "rgb(var(--contrast-disabled-rgb) / <alpha-value>)",
      },
      "table-head": {
        DEFAULT: "rgb(var(--table-head-color-rgb) / <alpha-value>)",
      },
      "table-even-row": {
        DEFAULT: "rgb(var(--table-even-row-color-rgb) / <alpha-value>)",
      },
      "table-odd-row": {
        DEFAULT: "rgb(var(--table-odd-row-color-rgb) / <alpha-value>)",
      },
      primary: {
        DEFAULT: "rgb(var(--primary-default-rgb) / <alpha-value>)",
        contrast: "rgb(var(--primary-contrast-rgb) / <alpha-value>)",
        tone: "rgb(var(--primary-tone-rgb) / <alpha-value>)",
      },
      active: {
        DEFAULT: "rgb(var(--active-default-rgb) / <alpha-value>)",
        contrast: "rgb(var(--active-contrast-rgb) / <alpha-value>)",
        tone: "rgb(var(--active-tone-rgb) / <alpha-value>)",
      },
      success: {
        DEFAULT: "rgb(var(--success-default-rgb) / <alpha-value>)",
        contrast: "rgb(var(--success-contrast-rgb) / <alpha-value>)",
        tone: "rgb(var(--success-tone-rgb) / <alpha-value>)",
      },
      warn: {
        DEFAULT: "rgb(var(--warn-default-rgb) / <alpha-value>)",
        contrast: "rgb(var(--warn-contrast-rgb) / <alpha-value>)",
        tone: "rgb(var(--warn-tone-rgb) / <alpha-value>)",
      },
      error: {
        DEFAULT: "rgb(var(--error-default-rgb) / <alpha-value>)",
        contrast: "rgb(var(--error-contrast-rgb) / <alpha-value>)",
        tone: "rgb(var(--error-tone-rgb) / <alpha-value>)",
      },
    },
    fontSize: {
      xs: ["0.75em", { lineHeight: "1.25" }],
      sm: ["0.875em", { lineHeight: "1.25" }],
      base: ["1em", { lineHeight: "1.25" }],
      lg: ["1.125em", { lineHeight: "1.25" }],
      xl: ["1.25em", { lineHeight: "1.25" }],
      "2xl": ["1.5em", { lineHeight: "1.25" }],
      "3xl": ["1.875em", { lineHeight: "1.25" }],
      "4xl": ["2.25em", { lineHeight: "1.25" }],
      "5xl": ["3em", { lineHeight: "1.25" }],
      "6xl": ["3.75em", { lineHeight: "1.25" }],
      "7xl": ["4.5em", { lineHeight: "1.25" }],
      "8xl": ["6em", { lineHeight: "1.25" }],
      "9xl": ["8em", { lineHeight: "1.25" }],
    },
    extend: {
      spacing: {
        "mobile-menu": "var(--mobile-menu)",
        sat: "env(safe-area-inset-top)",
        sar: "env(safe-area-inset-right)",
        sab: "calc(env(safe-area-inset-bottom) * 2)",
        sal: "env(safe-area-inset-left)",
      },
      minWidth: {
        xs: "20rem",
        sm: "24rem",
        md: "28rem",
        lg: "32rem",
        xl: "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem",
      },
      zIndex: {
        "popup-(50)": "50",
        "popup-(40)": "60",
        "popup-(30)": "70",
        "popup-(20)": "80",
        "popup-(10)": "90",
        popup: "100",
        "popup-10": "110",
        "popup-20": "120",
        "popup-30": "130",
        "popup-40": "140",
        "popup-50": "150",
        "menu-(50)": "150",
        "menu-(40)": "160",
        "menu-(30)": "170",
        "menu-(20)": "180",
        "menu-(10)": "190",
        menu: "200",
        "menu-10": "210",
        "menu-20": "220",
        "menu-30": "230",
        "menu-40": "240",
        "menu-50": "250",
        "popover-(50)": "250",
        "popover-(40)": "260",
        "popover-(30)": "270",
        "popover-(20)": "280",
        "popover-(10)": "290",
        popover: "300",
        "popover-10": "310",
        "popover-20": "320",
        "popover-30": "330",
        "popover-40": "340",
        "popover-50": "350",
        "modal-(50)": "350",
        "modal-(40)": "360",
        "modal-(30)": "370",
        "modal-(20)": "380",
        "modal-(10)": "390",
        modal: "400",
        "modal-10": "410",
        "modal-20": "420",
        "modal-30": "430",
        "modal-40": "440",
        "modal-50": "450",
        "alert-(50)": "450",
        "alert-(40)": "460",
        "alert-(30)": "470",
        "alert-(20)": "480",
        "alert-(10)": "490",
        alert: "500",
        "alert-10": "510",
        "alert-20": "520",
        "alert-30": "530",
        "alert-40": "540",
        "alert-50": "550",
      },
      gridTemplateColumns: {
        "fit-100": "repeat(auto-fit, minmax(min(100px, 100%), 1fr))",
        "fit-150": "repeat(auto-fit, minmax(min(150px, 100%), 1fr))",
        "fit-200": "repeat(auto-fit, minmax(min(200px, 100%), 1fr))",
        "fit-250": "repeat(auto-fit, minmax(min(250px, 100%), 1fr))",
        "fit-300": "repeat(auto-fit, minmax(min(300px, 100%), 1fr))",
        "fit-350": "repeat(auto-fit, minmax(min(350px, 100%), 1fr))",
        "fit-400": "repeat(auto-fit, minmax(min(400px, 100%), 1fr))",
        "fit-450": "repeat(auto-fit, minmax(min(450px, 100%), 1fr))",
        "fit-500": "repeat(auto-fit, minmax(min(500px, 100%), 1fr))",
        "fit-550": "repeat(auto-fit, minmax(min(550px, 100%), 1fr))",
        "fit-600": "repeat(auto-fit, minmax(min(600px, 100%), 1fr))",
        "fit-650": "repeat(auto-fit, minmax(min(650px, 100%), 1fr))",
        "fit-700": "repeat(auto-fit, minmax(min(700px, 100%), 1fr))",
        "fit-750": "repeat(auto-fit, minmax(min(750px, 100%), 1fr))",
        "fit-800": "repeat(auto-fit, minmax(min(800px, 100%), 1fr))",
        "fit-850": "repeat(auto-fit, minmax(min(850px, 100%), 1fr))",
        "fit-900": "repeat(auto-fit, minmax(min(900px, 100%), 1fr))",
        "fit-950": "repeat(auto-fit, minmax(min(950px, 100%), 1fr))",
        "fit-1000": "repeat(auto-fit, minmax(min(1000px, 100%), 1fr))",
        "fill-100": "repeat(auto-fill, minmax(min(100px, 100%), 1fr))",
        "fill-150": "repeat(auto-fill, minmax(min(150px, 100%), 1fr))",
        "fill-200": "repeat(auto-fill, minmax(min(200px, 100%), 1fr))",
        "fill-250": "repeat(auto-fill, minmax(min(250px, 100%), 1fr))",
        "fill-300": "repeat(auto-fill, minmax(min(300px, 100%), 1fr))",
        "fill-350": "repeat(auto-fill, minmax(min(350px, 100%), 1fr))",
        "fill-400": "repeat(auto-fill, minmax(min(400px, 100%), 1fr))",
        "fill-450": "repeat(auto-fill, minmax(min(450px, 100%), 1fr))",
        "fill-500": "repeat(auto-fill, minmax(min(500px, 100%), 1fr))",
        "fill-550": "repeat(auto-fill, minmax(min(550px, 100%), 1fr))",
        "fill-600": "repeat(auto-fill, minmax(min(600px, 100%), 1fr))",
        "fill-650": "repeat(auto-fill, minmax(min(650px, 100%), 1fr))",
        "fill-700": "repeat(auto-fill, minmax(min(700px, 100%), 1fr))",
        "fill-750": "repeat(auto-fill, minmax(min(750px, 100%), 1fr))",
        "fill-800": "repeat(auto-fill, minmax(min(800px, 100%), 1fr))",
        "fill-850": "repeat(auto-fill, minmax(min(850px, 100%), 1fr))",
        "fill-900": "repeat(auto-fill, minmax(min(900px, 100%), 1fr))",
        "fill-950": "repeat(auto-fill, minmax(min(950px, 100%), 1fr))",
        "fill-1000": "repeat(auto-fill, minmax(min(1000px, 100%), 1fr))",
      },
      gridTemplateRow: {
        "fit-150": "repeat(auto-fit, minmax(min(150px, 100%), 1fr))",
        "fit-200": "repeat(auto-fit, minmax(min(200px, 100%), 1fr))",
        "fit-250": "repeat(auto-fit, minmax(min(250px, 100%), 1fr))",
        "fit-300": "repeat(auto-fit, minmax(min(300px, 100%), 1fr))",
        "fit-100": "repeat(auto-fit, minmax(min(100px, 100%), 1fr))",
        "fit-350": "repeat(auto-fit, minmax(min(350px, 100%), 1fr))",
        "fit-400": "repeat(auto-fit, minmax(min(400px, 100%), 1fr))",
        "fit-450": "repeat(auto-fit, minmax(min(450px, 100%), 1fr))",
        "fit-500": "repeat(auto-fit, minmax(min(500px, 100%), 1fr))",
        "fit-550": "repeat(auto-fit, minmax(min(550px, 100%), 1fr))",
        "fit-600": "repeat(auto-fit, minmax(min(600px, 100%), 1fr))",
        "fit-650": "repeat(auto-fit, minmax(min(650px, 100%), 1fr))",
        "fit-700": "repeat(auto-fit, minmax(min(700px, 100%), 1fr))",
        "fit-750": "repeat(auto-fit, minmax(min(750px, 100%), 1fr))",
        "fit-800": "repeat(auto-fit, minmax(min(800px, 100%), 1fr))",
        "fit-850": "repeat(auto-fit, minmax(min(850px, 100%), 1fr))",
        "fit-900": "repeat(auto-fit, minmax(min(900px, 100%), 1fr))",
        "fit-950": "repeat(auto-fit, minmax(min(950px, 100%), 1fr))",
        "fit-1000": "repeat(auto-fit, minmax(min(1000px, 100%), 1fr))",
        "fill-150": "repeat(auto-fill, minmax(min(150px, 100%), 1fr))",
        "fill-200": "repeat(auto-fill, minmax(min(200px, 100%), 1fr))",
        "fill-250": "repeat(auto-fill, minmax(min(250px, 100%), 1fr))",
        "fill-300": "repeat(auto-fill, minmax(min(300px, 100%), 1fr))",
        "fill-100": "repeat(auto-fill, minmax(min(100px, 100%), 1fr))",
        "fill-350": "repeat(auto-fill, minmax(min(350px, 100%), 1fr))",
        "fill-400": "repeat(auto-fill, minmax(min(400px, 100%), 1fr))",
        "fill-450": "repeat(auto-fill, minmax(min(450px, 100%), 1fr))",
        "fill-500": "repeat(auto-fill, minmax(min(500px, 100%), 1fr))",
        "fill-550": "repeat(auto-fill, minmax(min(550px, 100%), 1fr))",
        "fill-600": "repeat(auto-fill, minmax(min(600px, 100%), 1fr))",
        "fill-650": "repeat(auto-fill, minmax(min(650px, 100%), 1fr))",
        "fill-700": "repeat(auto-fill, minmax(min(700px, 100%), 1fr))",
        "fill-750": "repeat(auto-fill, minmax(min(750px, 100%), 1fr))",
        "fill-800": "repeat(auto-fill, minmax(min(800px, 100%), 1fr))",
        "fill-850": "repeat(auto-fill, minmax(min(850px, 100%), 1fr))",
        "fill-900": "repeat(auto-fill, minmax(min(900px, 100%), 1fr))",
        "fill-950": "repeat(auto-fill, minmax(min(950px, 100%), 1fr))",
        "fill-1000": "repeat(auto-fill, minmax(min(1000px, 100%), 1fr))",
      },
    },
  },
};
export default config;
